site: cmaks
url: 
author: Clayton Maksymiuk
author: Clayton Maksymiuk
  name: Clayton Maksymiuk
  email: 
  url: 
  avatar: 
title: cmaks
description: cmaks
logo: 
image: 
twitter: claymaks
twitter:
  username: claymaks
  creator: claymaks
  card: summary
social:
  name: Clayton Maksymiuk
  links:
    - https://twitter.com/claymaks
    - https://github.com/claymaks
  
permalink: pretty
github_username: claymaks
url: https://cmaks.dev

baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - disqus-for-jekyll

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
