site: cmaks
url: 
author: Clayton Maksymiuk
author:
  name: Clayton Maksymiuk
  email: 
  url: 
  avatar: 
title: cmaks
description: cmaks
logo: 
image: 
twitter: claymaks
twitter:
  username: claymaks
  creator: claymaks
  card: summary
social:
  name: Clayton Maksymiuk
  links:
    - https://twitter.com/claymaks
    - https://github.com/claymaks
  
permalink: pretty

comments:
  provider: gitalk
  gitalk:
    clientID    : "e26593f9a3a79377f58d"
    clientSecret: "3dfdadb3c73f77ff6ba1686da5a5d48dc7deaadc"
    repository  : "cmaks.dev"
    owner       : "claymaks"
    admin: # Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
      - "claymaks"


baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - disqus-for-jekyll

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
